#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x2CE2036B4BF38A33 (rob@underbit.com)
#
Name     : libid3tag
Version  : 0.15.1b
Release  : 1
URL      : http://downloads.sourceforge.net/mad/libid3tag-0.15.1b.tar.gz
Source0  : http://downloads.sourceforge.net/mad/libid3tag-0.15.1b.tar.gz
Source99 : http://downloads.sourceforge.net/mad/libid3tag-0.15.1b.tar.gz.sign
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: libid3tag-lib
Requires: libid3tag-license
BuildRequires : gfortran
BuildRequires : pkgconfig(zlib)

%description
libid3tag - ID3 tag manipulation library
===============================================================================

%package dev
Summary: dev components for the libid3tag package.
Group: Development
Requires: libid3tag-lib
Provides: libid3tag-devel

%description dev
dev components for the libid3tag package.


%package lib
Summary: lib components for the libid3tag package.
Group: Libraries
Requires: libid3tag-license

%description lib
lib components for the libid3tag package.


%package license
Summary: license components for the libid3tag package.
Group: Default

%description license
license components for the libid3tag package.


%prep
%setup -q -n libid3tag-0.15.1b

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536447201
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1536447201
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libid3tag
cp COPYING %{buildroot}/usr/share/doc/libid3tag/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libid3tag.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libid3tag.so.0
/usr/lib64/libid3tag.so.0.3.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libid3tag/COPYING
